version: "3.6"
services:
  taipei_runner:
    build:
      context: .
      args: 
        DATABASE_URL_PSQL: "postgres://runner:runner@localhost:5432/taipei-runner"
        DATABASE_URL_MONGO: "mongodb://runner:runner@localhost:27017/taipei-runner"
        NODE_ENV: "development"
        PORT: 4000
    depends_on:
      - postgresdb
      - mongodb
    ports:
      - "4000:4000"
  postgresdb:
    image: postgres:13.2-alpine
    ports:
      - "5000:5432"
    environment: 
      POSTGRES_PASSWORD: taipeipassword
    volumes: 
      - ./db_init/postgres-initdb.sh:/docker-entrypoint-initdb.d/init.sh
      - ./dockerdata/postgres:/var/lib/postgresql/data
    restart: always
  mongodb:
    image: mongo
    ports:
      - "6000:27017"
    volumes:
      - ./db_init/init-mongo.js:/docker-entrypoint-initdb.d/init-mongo.js
      - ./dockerdata/mongo:/data/db