# This is a basic workflow to help you get started with Actions

name: DockerPub

# Controls when the action will run. 
on:
  # Triggers the workflow on push or pull request events but only for the sprint_4 branch
  push:
    branches: [ sprint_4,sprint_4.docker_push, master ]

  # Allows you to run this workflow manually from the Actions tab
  workflow_dispatch:

# A workflow run is made up of one or more jobs that can run sequentially or in parallel
jobs:
  # This workflow contains a single job called "build"
  build:
    # The type of runner that the job will run on
    runs-on: ubuntu-latest

    # Steps represent a sequence of tasks that will be executed as part of the job
    steps:
      # Checks-out your repository under $GITHUB_WORKSPACE, so your job can access it
      - uses: actions/checkout@v2

      # Runs a set of commands using the runners shell
      - name: YCR Login
        uses: docker/login-action@v1
        with:
          registry: cr.yandex
          username: json_key
          password: ${{ secrets.YCR_KEY_JSON }}
      - name: Build and YCR Push
        run: |
          docker-compose build
          docker tag taipei-runner_app cr.yandex/crpuidt47oer2qhm9a1m/taipei-runner_app:latest
          docker push cr.yandex/crpuidt47oer2qhm9a1m/taipei-runner_app:latest
      - name: SSH User Setup
        run: |
          mkdir -p ~/.ssh/
          echo "$SSH_PRIVATE_KEY" > private.key
          sudo chmod 600 private.key
          echo "$SSH_KNOWN_HOSTS" > ~/.ssh/known_hosts
        shell: bash
        env:
          SSH_PRIVATE_KEY: ${{secrets.YCR_SECRET}}
          SSH_KNOWN_HOSTS: ${{secrets.YCR_KNOWN_HOSTS}}
      - name: Copy db init
        run: |
          scp -i $SSH_KEY_PATH -r ${{ github.workspace }}/db_init/* ${{secrets.YCR_USERHOST}}:dbinit
        env:
          SSH_KEY_PATH: ${{ github.workspace }}/private.key    
      - name: Rebuild and Start Docker
        run: |
          ssh ${{secrets.YCR_USERHOST}} -i $SSH_KEY_PATH "docker pull ${{ secrets.YCR_PULL}} && docker-compose down && docker-compose up -d"
          curl https://taipei-runner-02.ya-praktikum.tech/ -i | grep status
        env:
          SSH_KEY_PATH: ${{ github.workspace }}/private.key
          
        